### ISSUE TITLE
Input to the Shellasync window doesn't get piped to the running program

### ISSUE THREAD

**Issue by Cypher1** [troydm/shellasync.vim#1]
There also seems to be no simple way of having continuous interaction with the program. :ShellSend helps, is there a way to do something more interactive?

**Comment by troydm** [comment]
@Cypher1 what do you mean by something interactive? there is :ShellTerminal command but it's more like interactive shell terminal. Can you describe what exactly you mean in more detail, also read help about :ShellSelect and :ShellSend commands about how to use them

**Comment by Cypher1** [comment]
I really just mean that stdin doesn't go from vim into the program running in async (e.g. in python or zsh or bash).

I have read :ShellSend but it doesn't give continuous I/O only single lines

**Comment by troydm** [comment]
@Cypher1 you can send a region to it, just visually select the code and type :,ShellSend. You can also send entire file by typing :%ShellSend

**Comment by Cypher1** [comment]
That helps but it would be great to have a continuous I/O option. Is there a computational or technical problem with doing this?

**Comment by troydm** [comment]
@Cypher1 I'm not sure what you mean by continuous I/O option. Can you describe the behavior in more detail?

**Comment by Cypher1** [comment]
So that you can type and the input goes to the program asynchronously, or at least on returns without having to type ":ShellSend" for every line

**Comment by troydm** [comment]
@Cypher1 you can do that with autocommand, type :he au for detailed explanation on how to do that and you can also read this http://learnvimscriptthehardway.stevelosh.com/chapters/12.html as a starting point tutorial. I don't see any point of implementing that kind of functionality in shellasync as it's very case specific and varies from programming language/prompt. It can be literally customized by any experienced vim user by himself if he needs to as he fits. I'm closing this issue

**Comment by Cypher1** [comment]
Autocommand could do it reasonably well, something like the following?
`au BufEnter shellasync* ShellSend`

It just seems messy when interacting with a program asynchronously is what this vim plugin is about, not at all case specific if you have interactive programs (not like make or gcc but things like fdisk, wifi-menu etc).
